return terraform with version in the response
eclipse-xpanse/terraform-boot pull request #149
Opened 2024-10-14 11:02 UTC by baixinsui

Related to https://github.com/eclipse-xpanse/xpanse/pull/2034

2024-10-14 12:14 UTC, swaroopar requested changes

2024-10-14 12:14 UTC, swaroopar commented on src/main/java/org/eclipse/xpanse/terraform/boot/models/response/TerraformResult.java
> +    @Schema(description = "Terraform with version which executed the command.")
terraformVersionUsed
The version of the Terraform binary used to execute scripts

2024-10-14 12:14 UTC, swaroopar commented on src/main/java/org/eclipse/xpanse/terraform/boot/models/plan/TerraformPlan.java
> +    String terraformWithVersion;
terraformVersionUsed
The version of the Terraform binary used to execute scripts

2024-10-14 12:14 UTC, swaroopar commented on src/main/java/org/eclipse/xpanse/terraform/boot/models/validation/TerraformValidationResult.java
> +    private String terraformWithVersion;
terraformVersionUsed
The version of the Terraform binary used to execute scripts

2024-10-15 02:02 UTC, Alice1319 commented
LGTM

2024-10-15 02:56 UTC, swaroopar approved these changes
LGTM

2024-10-15 02:56 UTC, merged