Optimize method for reading the files generated by the Terraform
eclipse-xpanse/terraform-boot pull request #162
Opened 2024-11-07 08:26 UTC by baixinsui

Fixed https://github.com/eclipse-xpanse/xpanse/issues/2068
Related to https://github.com/eclipse-xpanse/xpanse/pull/2094

2024-11-07 10:34 UTC, luoping-12345 commented
LGTM

2024-11-07 10:48 UTC, WangLiNaruto commented
LGTM

2024-11-07 11:43 UTC, yuanxiaojun987 commented
LGTM

2024-11-08 03:34 UTC, profoundwu commented
LGTM

2024-11-12 08:25 UTC, swaroopar requested changes
LGTM

2024-11-12 08:25 UTC, swaroopar commented on src/main/java/org/eclipse/xpanse/terraform/boot/terraform/service/ScriptsGitRepoManage.java
> +    private List<File> folderContainsScripts(String workspace,
its better we split this into two ->
getSourceFiles  and then pass it to validateIfFolderContainsTerraformScripts which returns void or throws exception. 
Then simply return the files returned by getSourceFiles.

2024-11-12 08:25 UTC, swaroopar commented on src/main/java/org/eclipse/xpanse/terraform/boot/terraform/service/ScriptsGitRepoManage.java
> +            throw new GitRepoCloneException(
Also better we throw another exception. GitRepoCloneException will not make sense here. 
If needed we can create a new custom exception.

2024-11-12 09:50 UTC, swaroopar approved these changes
LGTM

2024-11-12 09:50 UTC, merged